### ISSUE TITLE
iOS 11 Raise Text Never Come back

### ISSUE THREAD

**Issue by MukeshMuteja** [najanda89/RaisePlaceholder#1]
Hello,

This is working very well with iOS 10 and below but for iOS 11 i am getting many issues. like TEXT NEVER RETURN, when ENTER AGAIN A NEW TEXT ADDED which makes number of labels at TOP

**Comment by RameshSain** [comment]
Same issue here !!

**Comment by AabanTariq** [comment]
Same issue here, you got any solution?

**Comment by SunilAruruios** [comment]
Same issue

**Comment by LiveWireLabs** [comment]
Just update the following function in RaisePlaceHolder.Swift to solve this issue.

fileprivate func createPlaceholderLabel() { 
        if self.placeholderLabel == nil{
            let origin = self.frame.origin
            let label = UILabel(frame: CGRect(x: origin.x, y: origin.y, width: self.frame.size.width, height: 15.0))
            label.center = self.center
            label.text = ""
            label.font = UIFont.systemFont(ofSize: self.placeholderLabelFontSize)
            label.textColor = subjectColor
            
            if let superView = self.superview {
                superView.insertSubview(label, belowSubview: self)
            }
            
            self.placeholderLabel = label
        }
        
    }
