### ISSUE TITLE
init(colorLiteralRed:green:blue:alpha:)' is unavailable error

### ISSUE THREAD

**Issue by ismaiI1** [najanda89/RaisePlaceholder#2]
`'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals.`

error on : `placeholderLabel.textColor = UIColor(colorLiteralRed: 0, green: 0, blue: 0.0980392, alpha: 0.22)`

I add from storyboard.

**Comment by monang1611** [comment]
**`placeholderLabel.textColor = UIColor(colorLiteralRed: 0, green: 0, blue: 0.0980392, alpha: 0.22)`**
Just Change this line 
**`placeholderLabel.textColor = UIColor(red: 0, green: 0, blue: 0.0980392, alpha: 0.22)`**

**Comment by ismaiI1** [comment]
Thanks..
